import {
  Bed,
  Bath,
  Users,
  Wifi,
  Lock,
  Sun,
  Coffee,
  Wind,
  Shirt,
  Waves,
  Star,
  Shield,
  Camera,
  Clock,
  MapPin,
  Heart,
  Check,
  Award,
  UtensilsCrossed,
  Flame,
  Compass,
  Anchor,
  Leaf,
  Home,
  Eye,
  Car,
} from 'lucide-react'

export const iconOptions = [
  { label: 'Bed', value: 'bed' },
  { label: 'Bath', value: 'bath' },
  { label: 'Users', value: 'users' },
  { label: 'Wi-Fi', value: 'wifi' },
  { label: 'Lock', value: 'lock' },
  { label: 'Sun', value: 'sun' },
  { label: 'Coffee', value: 'coffee' },
  { label: 'Wind', value: 'wind' },
  { label: 'Shirt', value: 'shirt' },
  { label: 'Waves', value: 'waves' },
  { label: 'Star', value: 'star' },
  { label: 'Shield', value: 'shield' },
  { label: 'Camera', value: 'camera' },
  { label: 'Clock', value: 'clock' },
  { label: 'Map Pin', value: 'map-pin' },
  { label: 'Heart', value: 'heart' },
  { label: 'Check', value: 'check' },
  { label: 'Award', value: 'award' },
  { label: 'Restaurant', value: 'utensils' },
  { label: 'Flame', value: 'flame' },
  { label: 'Compass', value: 'compass' },
  { label: 'Anchor', value: 'anchor' },
  { label: 'Leaf', value: 'leaf' },
  { label: 'Home', value: 'home' },
  { label: 'Eye', value: 'eye' },
  { label: 'Car', value: 'car' },
] as const

export type IconValue = (typeof iconOptions)[number]['value']

export const ICON_MAP: Record<string, React.ComponentType<{ className?: string }>> = {
  bed: Bed,
  bath: Bath,
  users: Users,
  wifi: Wifi,
  lock: Lock,
  sun: Sun,
  coffee: Coffee,
  wind: Wind,
  shirt: Shirt,
  waves: Waves,
  star: Star,
  shield: Shield,
  camera: Camera,
  clock: Clock,
  'map-pin': MapPin,
  heart: Heart,
  check: Check,
  award: Award,
  utensils: UtensilsCrossed,
  flame: Flame,
  compass: Compass,
  anchor: Anchor,
  leaf: Leaf,
  home: Home,
  eye: Eye,
  car: Car,
}

export function getIcon(value: string | null | undefined): React.ComponentType<{ className?: string }> {
  if (!value) return Star
  return ICON_MAP[value] || Star
}
