/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    bookings: Booking;
    blog: Blog;
    rooms: Room;
    packages: Package;
    activities: Activity;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    bookings: BookingsSelect<false> | BookingsSelect<true>;
    blog: BlogSelect<false> | BlogSelect<true>;
    rooms: RoomsSelect<false> | RoomsSelect<true>;
    packages: PackagesSelect<false> | PackagesSelect<true>;
    activities: ActivitiesSelect<false> | ActivitiesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('en' | 'fr') | ('en' | 'fr')[];
  globals: {
    homepage: Homepage;
    'about-page': AboutPage;
    'rooms-page': RoomsPage;
    'surf-page': SurfPage;
    'packages-page': PackagesPage;
    'restaurant-page': RestaurantPage;
    'blog-page': BlogPage;
    'contact-page': ContactPage;
    transfers: Transfer;
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    homepage: HomepageSelect<false> | HomepageSelect<true>;
    'about-page': AboutPageSelect<false> | AboutPageSelect<true>;
    'rooms-page': RoomsPageSelect<false> | RoomsPageSelect<true>;
    'surf-page': SurfPageSelect<false> | SurfPageSelect<true>;
    'packages-page': PackagesPageSelect<false> | PackagesPageSelect<true>;
    'restaurant-page': RestaurantPageSelect<false> | RestaurantPageSelect<true>;
    'blog-page': BlogPageSelect<false> | BlogPageSelect<true>;
    'contact-page': ContactPageSelect<false> | ContactPageSelect<true>;
    transfers: TransfersSelect<false> | TransfersSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: 'en' | 'fr';
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  /**
   * Optional — can be added later. Improves accessibility and SEO.
   */
  alt?: string | null;
  _key?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      _key?: string | null;
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      _key?: string | null;
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      _key?: string | null;
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero2x?: {
      _key?: string | null;
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bookings".
 */
export interface Booking {
  id: string;
  customerName: string;
  customerEmail: string;
  customerPhone: string;
  /**
   * Link to package in database (if exists)
   */
  package?: (string | null) | Package;
  /**
   * Name of the booked package or activity
   */
  flightTitle: string;
  flightType: 'package' | 'stay-eat' | 'full-surf' | 'surf-only' | 'room' | 'surf-lesson' | 'rental' | 'other';
  date: string;
  numberOfAdults: number;
  numberOfChildren: number;
  status: 'pending' | 'confirmed' | 'completed' | 'cancelled';
  totalPrice: number;
  paymentStatus?: ('unpaid' | 'partial' | 'paid' | 'refunded') | null;
  pickupLocation?: string | null;
  /**
   * Whether customer provided pickup location at booking time
   */
  pickupLocationKnown?: boolean | null;
  /**
   * Auto-generated breakdown of what the customer booked (rooms, activities, transfer…). Editable — update if the customer requests changes after booking.
   */
  bookingSummary?: string | null;
  /**
   * Customer-provided notes (allergies, arrival time, etc.)
   */
  specialRequests?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "packages".
 */
export interface Package {
  id: string;
  title: string;
  /**
   * URL-friendly name, e.g. "stay-eat", "full-surf"
   */
  slug: string;
  /**
   * e.g. "Best Value", "Most Popular"
   */
  badge?: string | null;
  /**
   * e.g. "Best Value", "Most Popular", "Quick Start"
   */
  category?: string | null;
  highlight?: boolean | null;
  order?: number | null;
  images?:
    | {
        image: string | Media;
        alt?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Base price in EUR (e.g. 31)
   */
  price: number;
  /**
   * e.g. "/ night", "/ session"
   */
  priceUnit?: string | null;
  /**
   * e.g. "Per Night", "Per Session"
   */
  duration?: string | null;
  features?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  tagline?: string | null;
  description: string;
  /**
   * Extended description for the detail page
   */
  longDescription?: string | null;
  highlights?:
    | {
        icon?:
          | (
              | 'bed'
              | 'bath'
              | 'users'
              | 'wifi'
              | 'lock'
              | 'sun'
              | 'coffee'
              | 'wind'
              | 'shirt'
              | 'waves'
              | 'star'
              | 'shield'
              | 'camera'
              | 'clock'
              | 'map-pin'
              | 'heart'
              | 'check'
              | 'award'
              | 'utensils'
              | 'flame'
              | 'compass'
              | 'anchor'
              | 'leaf'
              | 'home'
              | 'eye'
              | 'car'
            )
          | null;
        title: string;
        desc?: string | null;
        id?: string | null;
      }[]
    | null;
  includes?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  notIncludes?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  schedule?:
    | {
        time: string;
        icon?:
          | (
              | 'bed'
              | 'bath'
              | 'users'
              | 'wifi'
              | 'lock'
              | 'sun'
              | 'coffee'
              | 'wind'
              | 'shirt'
              | 'waves'
              | 'star'
              | 'shield'
              | 'camera'
              | 'clock'
              | 'map-pin'
              | 'heart'
              | 'check'
              | 'award'
              | 'utensils'
              | 'flame'
              | 'compass'
              | 'anchor'
              | 'leaf'
              | 'home'
              | 'eye'
              | 'car'
            )
          | null;
        label: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Rooms available on the package and booking pages. The included-room capacity setting determines whether each room is free or charged at its normal nightly price.
   */
  linkedRooms?: (string | Room)[] | null;
  /**
   * Controls how the package price is multiplied in checkout.
   */
  pricingBasis: 'per-person' | 'fixed';
  /**
   * Checkout is set automatically from the selected check-in date.
   */
  durationNights: number;
  /**
   * Rooms with this guest capacity or less are included. Larger rooms keep their normal nightly price.
   */
  includedRoomMaxGuests: number;
  includesBreakfast?: boolean | null;
  includedGroupSurfLessons?: number | null;
  includedPrivateSurfLessons?: number | null;
  ctaText?: string | null;
  /**
   * WhatsApp pre-filled message
   */
  waMessage?: string | null;
  seo?: {
    /**
     * Shown in browser tab and search engines. Recommended: 50-60 characters.
     */
    metaTitle?: string | null;
    /**
     * Shown in search results. Recommended: 150-160 characters.
     */
    metaDescription?: string | null;
    /**
     * Comma-separated keywords (optional, low SEO impact today).
     */
    keywords?: string | null;
    /**
     * Shown when the page is shared on Facebook, Twitter, WhatsApp. Recommended: 1200x630px.
     */
    ogImage?: (string | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rooms".
 */
export interface Room {
  id: string;
  name: string;
  /**
   * URL-friendly name, e.g. "single", "female-dorm"
   */
  slug: string;
  /**
   * e.g. "Most Popular", "Best Value", "Premium"
   */
  badge?: string | null;
  /**
   * Display order (lower = first)
   */
  order?: number | null;
  /**
   * e.g. "1 guest · Private room · Shared bathroom"
   */
  detail?: string | null;
  images?:
    | {
        image: string | Media;
        alt?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Price per night in EUR (e.g. 18)
   */
  price: number;
  /**
   * Price with breakfast in EUR (e.g. 22). Leave empty if N/A.
   */
  priceBreakfast?: number | null;
  /**
   * e.g. "4.9"
   */
  rating?: string | null;
  /**
   * e.g. "Your private retreat in Imsouane"
   */
  tagline?: string | null;
  description: string;
  guests: number;
  /**
   * e.g. "1 single bed", "1 double bed"
   */
  beds: string;
  /**
   * e.g. "Shared bathroom", "Private shower"
   */
  bathroom: string;
  amenities?:
    | {
        icon?:
          | (
              | 'bed'
              | 'bath'
              | 'users'
              | 'wifi'
              | 'lock'
              | 'sun'
              | 'coffee'
              | 'wind'
              | 'shirt'
              | 'waves'
              | 'star'
              | 'shield'
              | 'camera'
              | 'clock'
              | 'map-pin'
              | 'heart'
              | 'check'
              | 'award'
              | 'utensils'
              | 'flame'
              | 'compass'
              | 'anchor'
              | 'leaf'
              | 'home'
              | 'eye'
              | 'car'
            )
          | null;
        label: string;
        id?: string | null;
      }[]
    | null;
  highlights?:
    | {
        icon?:
          | (
              | 'bed'
              | 'bath'
              | 'users'
              | 'wifi'
              | 'lock'
              | 'sun'
              | 'coffee'
              | 'wind'
              | 'shirt'
              | 'waves'
              | 'star'
              | 'shield'
              | 'camera'
              | 'clock'
              | 'map-pin'
              | 'heart'
              | 'check'
              | 'award'
              | 'utensils'
              | 'flame'
              | 'compass'
              | 'anchor'
              | 'leaf'
              | 'home'
              | 'eye'
              | 'car'
            )
          | null;
        title: string;
        desc?: string | null;
        id?: string | null;
      }[]
    | null;
  houseRules?:
    | {
        rule: string;
        id?: string | null;
      }[]
    | null;
  /**
   * WhatsApp pre-filled message
   */
  waMessage?: string | null;
  seo?: {
    /**
     * Shown in browser tab and search engines. Recommended: 50-60 characters.
     */
    metaTitle?: string | null;
    /**
     * Shown in search results. Recommended: 150-160 characters.
     */
    metaDescription?: string | null;
    /**
     * Comma-separated keywords (optional, low SEO impact today).
     */
    keywords?: string | null;
    /**
     * Shown when the page is shared on Facebook, Twitter, WhatsApp. Recommended: 1200x630px.
     */
    ogImage?: (string | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog".
 */
export interface Blog {
  id: string;
  title: string;
  /**
   * URL-friendly identifier (e.g., "best-time-for-balloon-rides")
   */
  slug: string;
  /**
   * Short summary for blog cards (150-200 characters recommended)
   */
  excerpt: string;
  featuredImage: string | Media;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  category:
    | 'travel-tips'
    | 'experience-stories'
    | 'marrakech-guide'
    | 'photography'
    | 'safety-faqs'
    | 'behind-the-scenes';
  status: 'draft' | 'published';
  /**
   * Add relevant tags for better discoverability
   */
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  author: string;
  publishedAt: string;
  /**
   * Estimated reading time in minutes
   */
  readingTime?: number | null;
  seo?: {
    /**
     * Leave empty to use blog title
     */
    metaTitle?: string | null;
    /**
     * Leave empty to use excerpt
     */
    metaDescription?: string | null;
    keywords?:
      | {
          keyword: string;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Select related blog posts to show at the bottom
   */
  relatedPosts?: (string | Blog)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "activities".
 */
export interface Activity {
  id: string;
  title: string;
  activityType?: ('lesson' | 'rental') | null;
  slug: string;
  /**
   * e.g. "All Levels", "Most Popular", "Best Value"
   */
  badge?: string | null;
  order?: number | null;
  images?:
    | {
        image: string | Media;
        alt?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Price in EUR (e.g. 18)
   */
  price: number;
  /**
   * e.g. "/ session", "/ day", "/ person"
   */
  priceUnit?: string | null;
  /**
   * e.g. "2h Session", "Per Day"
   */
  duration?: string | null;
  features?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  /**
   * WhatsApp or booking URL
   */
  bookingLink?: string | null;
  bookingText?: string | null;
  tagline?: string | null;
  description: string;
  /**
   * e.g. "All levels", "Beginner"
   */
  level?: string | null;
  /**
   * e.g. "1 person", "2-4 people", "Large group"
   */
  groupSize?: string | null;
  includes?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  notIncluded?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  highlights?:
    | {
        icon?:
          | (
              | 'bed'
              | 'bath'
              | 'users'
              | 'wifi'
              | 'lock'
              | 'sun'
              | 'coffee'
              | 'wind'
              | 'shirt'
              | 'waves'
              | 'star'
              | 'shield'
              | 'camera'
              | 'clock'
              | 'map-pin'
              | 'heart'
              | 'check'
              | 'award'
              | 'utensils'
              | 'flame'
              | 'compass'
              | 'anchor'
              | 'leaf'
              | 'home'
              | 'eye'
              | 'car'
            )
          | null;
        title: string;
        desc?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * WhatsApp pre-filled message
   */
  waMessage?: string | null;
  seo?: {
    /**
     * Shown in browser tab and search engines. Recommended: 50-60 characters.
     */
    metaTitle?: string | null;
    /**
     * Shown in search results. Recommended: 150-160 characters.
     */
    metaDescription?: string | null;
    /**
     * Comma-separated keywords (optional, low SEO impact today).
     */
    keywords?: string | null;
    /**
     * Shown when the page is shared on Facebook, Twitter, WhatsApp. Recommended: 1200x630px.
     */
    ogImage?: (string | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'bookings';
        value: string | Booking;
      } | null)
    | ({
        relationTo: 'blog';
        value: string | Blog;
      } | null)
    | ({
        relationTo: 'rooms';
        value: string | Room;
      } | null)
    | ({
        relationTo: 'packages';
        value: string | Package;
      } | null)
    | ({
        relationTo: 'activities';
        value: string | Activity;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  _key?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              _key?: T;
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              _key?: T;
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              _key?: T;
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero2x?:
          | T
          | {
              _key?: T;
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bookings_select".
 */
export interface BookingsSelect<T extends boolean = true> {
  customerName?: T;
  customerEmail?: T;
  customerPhone?: T;
  package?: T;
  flightTitle?: T;
  flightType?: T;
  date?: T;
  numberOfAdults?: T;
  numberOfChildren?: T;
  status?: T;
  totalPrice?: T;
  paymentStatus?: T;
  pickupLocation?: T;
  pickupLocationKnown?: T;
  bookingSummary?: T;
  specialRequests?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog_select".
 */
export interface BlogSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  featuredImage?: T;
  content?: T;
  category?: T;
  status?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  author?: T;
  publishedAt?: T;
  readingTime?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        keywords?:
          | T
          | {
              keyword?: T;
              id?: T;
            };
      };
  relatedPosts?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rooms_select".
 */
export interface RoomsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  badge?: T;
  order?: T;
  detail?: T;
  images?:
    | T
    | {
        image?: T;
        alt?: T;
        id?: T;
      };
  price?: T;
  priceBreakfast?: T;
  rating?: T;
  tagline?: T;
  description?: T;
  guests?: T;
  beds?: T;
  bathroom?: T;
  amenities?:
    | T
    | {
        icon?: T;
        label?: T;
        id?: T;
      };
  highlights?:
    | T
    | {
        icon?: T;
        title?: T;
        desc?: T;
        id?: T;
      };
  houseRules?:
    | T
    | {
        rule?: T;
        id?: T;
      };
  waMessage?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        keywords?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "packages_select".
 */
export interface PackagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  badge?: T;
  category?: T;
  highlight?: T;
  order?: T;
  images?:
    | T
    | {
        image?: T;
        alt?: T;
        id?: T;
      };
  price?: T;
  priceUnit?: T;
  duration?: T;
  features?:
    | T
    | {
        label?: T;
        id?: T;
      };
  tagline?: T;
  description?: T;
  longDescription?: T;
  highlights?:
    | T
    | {
        icon?: T;
        title?: T;
        desc?: T;
        id?: T;
      };
  includes?:
    | T
    | {
        item?: T;
        id?: T;
      };
  notIncludes?:
    | T
    | {
        item?: T;
        id?: T;
      };
  schedule?:
    | T
    | {
        time?: T;
        icon?: T;
        label?: T;
        id?: T;
      };
  linkedRooms?: T;
  pricingBasis?: T;
  durationNights?: T;
  includedRoomMaxGuests?: T;
  includesBreakfast?: T;
  includedGroupSurfLessons?: T;
  includedPrivateSurfLessons?: T;
  ctaText?: T;
  waMessage?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        keywords?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "activities_select".
 */
export interface ActivitiesSelect<T extends boolean = true> {
  title?: T;
  activityType?: T;
  slug?: T;
  badge?: T;
  order?: T;
  images?:
    | T
    | {
        image?: T;
        alt?: T;
        id?: T;
      };
  price?: T;
  priceUnit?: T;
  duration?: T;
  features?:
    | T
    | {
        label?: T;
        id?: T;
      };
  bookingLink?: T;
  bookingText?: T;
  tagline?: T;
  description?: T;
  level?: T;
  groupSize?: T;
  includes?:
    | T
    | {
        item?: T;
        id?: T;
      };
  notIncluded?:
    | T
    | {
        item?: T;
        id?: T;
      };
  highlights?:
    | T
    | {
        icon?: T;
        title?: T;
        desc?: T;
        id?: T;
      };
  waMessage?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        keywords?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Edit the main homepage content — all sections that appear on the Lina House landing page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage".
 */
export interface Homepage {
  id: string;
  /**
   * Search engine and social share metadata for the homepage
   */
  seo?: {
    /**
     * Shown in browser tab and search engines. Recommended: 50-60 characters.
     */
    metaTitle?: string | null;
    /**
     * Shown in search results. Recommended: 150-160 characters.
     */
    metaDescription?: string | null;
    /**
     * Comma-separated keywords (optional, low SEO impact today).
     */
    keywords?: string | null;
    /**
     * Shown when the page is shared on Facebook, Twitter, WhatsApp. Recommended: 1200x630px.
     */
    ogImage?: (string | null) | Media;
  };
  /**
   * The full-screen banner at the top of the homepage
   */
  heroSection?: {
    /**
     * Fallback/poster image when no video URL is set (recommended: 1920x1080 or larger).
     */
    backgroundImage?: (string | null) | Media;
    /**
     * Optional. Cloudinary video URL used on tablets & desktops (≥768px). Only this file is downloaded on desktop — the mobile URL is never loaded. Example: https://res.cloudinary.com/<cloud>/video/upload/q_auto,vc_auto,w_1280,f_auto,fps_30/<PUBLIC_ID>.mp4
     */
    heroVideoUrl?: string | null;
    /**
     * Optional. Cloudinary video URL used on phones (<768px). Only this file is downloaded on mobile. If empty, the desktop URL is used on mobile too. Recommended: smaller width (e.g. w_720) and portrait crop. Example: https://res.cloudinary.com/<cloud>/video/upload/q_auto,vc_auto,w_720,f_auto,fps_30/<PUBLIC_ID>.mp4
     */
    heroVideoMobileUrl?: string | null;
    /**
     * Optional. WebM version of the desktop video. Chrome/Firefox/Edge will prefer this (30-50% smaller than MP4). Safari falls back to MP4 automatically. Leave empty to skip.
     */
    heroVideoWebmUrl?: string | null;
    /**
     * Optional. WebM version of the mobile video. If empty, the desktop WebM is used on mobile too (if present).
     */
    heroVideoMobileWebmUrl?: string | null;
    /**
     * Leave empty — the first frame of the Cloudinary video is used automatically. Only set this if you want a specific still image. Example of a custom frame: https://res.cloudinary.com/<cloud>/video/upload/so_2,w_1280,q_auto,f_auto/<PUBLIC_ID>.jpg
     */
    heroPosterUrl?: string | null;
    headline?: string | null;
    /**
     * Large text below the headline
     */
    tagline?: string | null;
    description?: string | null;
    /**
     * Small icon+label items shown below the description (max 4)
     */
    highlights?:
      | {
          icon: 'waves' | 'utensils' | 'star' | 'sun' | 'wifi' | 'shield' | 'map-pin' | 'heart';
          label: string;
          id?: string | null;
        }[]
      | null;
    primaryButtonText?: string | null;
    primaryButtonLink?: string | null;
    secondaryButtonText?: string | null;
    secondaryButtonLink?: string | null;
  };
  /**
   * The "Welcome to Lina House" section with stats and experience card
   */
  aboutSection?: {
    title?: string | null;
    /**
     * The italic serif coral phrase after the title. Rendered after a space.
     */
    titleAccent?: string | null;
    description?: string | null;
    stats?:
      | {
          value: string;
          label: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Background image for the experience card on the right
     */
    experienceImage?: (string | null) | Media;
    experienceTitle?: string | null;
    experienceFeatures?:
      | {
          title: string;
          description: string;
          id?: string | null;
        }[]
      | null;
    experienceButtonText?: string | null;
    experienceButtonLink?: string | null;
  };
  /**
   * The "Where you'll stay" section showing all room types
   */
  roomsSection?: {
    title?: string | null;
    /**
     * The italic serif coral phrase after the title. Rendered after a space.
     */
    titleAccent?: string | null;
    /**
     * Pick which rooms to feature on the homepage. Leave empty to show all rooms sorted by order.
     */
    featuredRooms?: (string | Room)[] | null;
  };
  /**
   * Surf lessons and board rental cards
   */
  surfSection?: {
    title?: string | null;
    /**
     * The italic serif coral phrase after the title. Rendered after a space.
     */
    titleAccent?: string | null;
    description?: string | null;
    /**
     * Pick which activities to feature on the homepage. Leave empty to show all activities sorted by order.
     */
    featuredActivities?: (string | Activity)[] | null;
  };
  /**
   * Stay packages with pricing and features
   */
  packagesSection?: {
    title?: string | null;
    /**
     * The italic serif coral phrase after the title. Rendered after a space.
     */
    titleAccent?: string | null;
    description?: string | null;
    /**
     * Pick which packages to feature on the homepage. Leave empty to show all packages sorted by order.
     */
    featuredPackages?: (string | Package)[] | null;
  };
  /**
   * Surfboard + wetsuit rentals card with inline booking form
   */
  rentalsSection?: {
    title?: string | null;
    /**
     * The italic serif coral phrase after the title. Rendered after a space.
     */
    titleAccent?: string | null;
    description?: string | null;
    fromPriceBadge?: string | null;
    soloNote?: string | null;
    groupNote?: string | null;
    cardTitle?: string | null;
    cardDescription?: string | null;
    features?:
      | {
          label: string;
          icon?: ('waves' | 'shield' | 'check' | 'star') | null;
          id?: string | null;
        }[]
      | null;
    displayPrice?: number | null;
    perDayLabel?: string | null;
    soloPricePerDay?: number | null;
    groupPricePerDay?: number | null;
    bookNowText?: string | null;
    form?: {
      equipment?: string | null;
      boardOnly?: string | null;
      wetsuitOnly?: string | null;
      both?: string | null;
      startDate?: string | null;
      endDate?: string | null;
      quantity?: string | null;
      fullName?: string | null;
      email?: string | null;
      phone?: string | null;
      days?: string | null;
      day?: string | null;
      perPerson?: string | null;
      submit?: string | null;
      submitting?: string | null;
      successTitle?: string | null;
      successMessage?: string | null;
      errorGeneric?: string | null;
      errorDateOrder?: string | null;
    };
  };
  /**
   * Restaurant hero, meal cards, and food philosophy
   */
  restaurantSection?: {
    /**
     * Background image for the restaurant hero banner
     */
    heroImage?: (string | null) | Media;
    title?: string | null;
    /**
     * The italic serif coral phrase after the title. Rendered after a space.
     */
    titleAccent?: string | null;
    description?: string | null;
    meals?:
      | {
          title: string;
          time?: string | null;
          description?: string | null;
          image?: (string | null) | Media;
          id?: string | null;
        }[]
      | null;
    /**
     * Icon badges shown below the meal cards
     */
    philosophy?:
      | {
          title: string;
          description?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * The dark horizontal strip with key stats/features
   */
  featureStrip?: {
    features?:
      | {
          value: string;
          label: string;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Guest reviews and rating badges
   */
  reviewsSection?: {
    title?: string | null;
    /**
     * The italic serif coral phrase after the title. Rendered after a space.
     */
    titleAccent?: string | null;
    ratingBadges?:
      | {
          score: string;
          source: string;
          label?: string | null;
          id?: string | null;
        }[]
      | null;
    reviews?:
      | {
          name: string;
          from?: string | null;
          quote: string;
          dark?: boolean | null;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Bento-grid photo gallery with lightbox
   */
  gallerySection?: {
    title?: string | null;
    /**
     * The italic serif coral phrase after the title. Rendered after a space.
     */
    titleAccent?: string | null;
    /**
     * Drag and drop multiple images at once. Alt text can be added later in the Media library.
     */
    images?: (string | Media)[] | null;
    instagramUrl?: string | null;
  };
  /**
   * Map, contact info, and directions
   */
  locationSection?: {
    title?: string | null;
    /**
     * The italic serif coral phrase after the title. Rendered after a space.
     */
    titleAccent?: string | null;
    description?: string | null;
    /**
     * The full Google Maps embed URL (from Maps > Share > Embed)
     */
    mapEmbedUrl?: string | null;
    phone?: string | null;
    email?: string | null;
    /**
     * Used for WhatsApp links — format: 212772228120
     */
    whatsappNumber?: string | null;
    address?: string | null;
    instagramUrl?: string | null;
    tiktokUrl?: string | null;
    routes?:
      | {
          from: string;
          time: string;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Footer content and brand information
   */
  footer?: {
    brandName?: string | null;
    brandTagline?: string | null;
    brandDescription?: string | null;
    copyrightText?: string | null;
    designCredit?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Edit the About page content — hero, story, experience, feature strip, experience cards, FAQ, and CTA sections.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page".
 */
export interface AboutPage {
  id: string;
  seo?: {
    /**
     * Shown in browser tab and search engines. Recommended: 50-60 characters.
     */
    metaTitle?: string | null;
    /**
     * Shown in search results. Recommended: 150-160 characters.
     */
    metaDescription?: string | null;
    /**
     * Comma-separated keywords (optional, low SEO impact today).
     */
    keywords?: string | null;
    /**
     * Shown when the page is shared on Facebook, Twitter, WhatsApp. Recommended: 1200x630px.
     */
    ogImage?: (string | null) | Media;
  };
  heroSection?: {
    eyebrow?: string | null;
    title?: string | null;
    description?: string | null;
    ratingValue?: string | null;
    ratingLabel?: string | null;
    location?: string | null;
    /**
     * Recommended: 1920x1080 or larger
     */
    backgroundImage?: (string | null) | Media;
    imageAlt?: string | null;
  };
  storySection?: {
    eyebrow?: string | null;
    title?: string | null;
    ratingText?: string | null;
    description?: string | null;
    /**
     * Image displayed alongside the story text
     */
    image?: (string | null) | Media;
    imageAlt?: string | null;
    /**
     * Checkmark feature list displayed below the description
     */
    features?:
      | {
          label: string;
          id?: string | null;
        }[]
      | null;
  };
  experienceSection?: {
    eyebrow?: string | null;
    title?: string | null;
    ratingText?: string | null;
    description1?: string | null;
    description2?: string | null;
    /**
     * Image displayed alongside the experience text
     */
    image?: (string | null) | Media;
    imageAlt?: string | null;
    /**
     * Checkmark feature list displayed below the description
     */
    features?:
      | {
          label: string;
          id?: string | null;
        }[]
      | null;
  };
  featureStrip?: {
    /**
     * Each item shows an icon, a value, and a label
     */
    items?:
      | {
          icon:
            | 'bed'
            | 'bath'
            | 'users'
            | 'wifi'
            | 'lock'
            | 'sun'
            | 'coffee'
            | 'wind'
            | 'shirt'
            | 'waves'
            | 'star'
            | 'shield'
            | 'camera'
            | 'clock'
            | 'map-pin'
            | 'heart'
            | 'check'
            | 'award'
            | 'utensils'
            | 'flame'
            | 'compass'
            | 'anchor'
            | 'leaf'
            | 'home'
            | 'eye'
            | 'car';
          value: string;
          label: string;
          id?: string | null;
        }[]
      | null;
  };
  experienceCards?: {
    eyebrow?: string | null;
    title?: string | null;
    subtitle?: string | null;
    /**
     * Each card has an icon, title, description, image, and feature list
     */
    cards?:
      | {
          icon:
            | 'bed'
            | 'bath'
            | 'users'
            | 'wifi'
            | 'lock'
            | 'sun'
            | 'coffee'
            | 'wind'
            | 'shirt'
            | 'waves'
            | 'star'
            | 'shield'
            | 'camera'
            | 'clock'
            | 'map-pin'
            | 'heart'
            | 'check'
            | 'award'
            | 'utensils'
            | 'flame'
            | 'compass'
            | 'anchor'
            | 'leaf'
            | 'home'
            | 'eye'
            | 'car';
          title: string;
          description: string;
          image?: (string | null) | Media;
          features?:
            | {
                label: string;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
  };
  faqSection?: {
    eyebrow?: string | null;
    title?: string | null;
    contactText?: string | null;
    whatsappUrl?: string | null;
    whatsappLabel?: string | null;
    /**
     * Add question/answer pairs
     */
    faqs?:
      | {
          question: string;
          answer: string;
          id?: string | null;
        }[]
      | null;
  };
  ctaSection?: {
    title?: string | null;
    subtitle?: string | null;
    /**
     * Background image for the CTA banner
     */
    backgroundImage?: (string | null) | Media;
    primaryButtonText?: string | null;
    primaryButtonLink?: string | null;
    secondaryButtonText?: string | null;
    secondaryButtonLink?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Edit the /rooms page — page header and "Save with packages" CTA.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rooms-page".
 */
export interface RoomsPage {
  id: string;
  /**
   * Search engine and social share metadata for this page
   */
  seo?: {
    /**
     * Shown in browser tab and search engines. Recommended: 50-60 characters.
     */
    metaTitle?: string | null;
    /**
     * Shown in search results. Recommended: 150-160 characters.
     */
    metaDescription?: string | null;
    /**
     * Comma-separated keywords (optional, low SEO impact today).
     */
    keywords?: string | null;
    /**
     * Shown when the page is shared on Facebook, Twitter, WhatsApp. Recommended: 1200x630px.
     */
    ogImage?: (string | null) | Media;
  };
  headerSection?: {
    breadcrumbLabel?: string | null;
    title?: string | null;
    subtitle?: string | null;
    ratingScore?: string | null;
    ratingSource?: string | null;
    infoChip1?: string | null;
    infoChip2?: string | null;
  };
  packagesCta?: {
    title?: string | null;
    description?: string | null;
    buttonText?: string | null;
    buttonLink?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Edit the /surf page — page header, rentals & transport cards, surf spots, typical day timeline, and final CTA.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "surf-page".
 */
export interface SurfPage {
  id: string;
  /**
   * Search engine and social share metadata for this page
   */
  seo?: {
    /**
     * Shown in browser tab and search engines. Recommended: 50-60 characters.
     */
    metaTitle?: string | null;
    /**
     * Shown in search results. Recommended: 150-160 characters.
     */
    metaDescription?: string | null;
    /**
     * Comma-separated keywords (optional, low SEO impact today).
     */
    keywords?: string | null;
    /**
     * Shown when the page is shared on Facebook, Twitter, WhatsApp. Recommended: 1200x630px.
     */
    ogImage?: (string | null) | Media;
  };
  headerSection?: {
    breadcrumbLabel?: string | null;
    title?: string | null;
    subtitle?: string | null;
    ratingScore?: string | null;
    ratingSource?: string | null;
    infoChip1?: string | null;
    infoChip2?: string | null;
  };
  rentalsSection?: {
    title?: string | null;
    subtitle?: string | null;
    surfboardCard?: {
      title?: string | null;
      description?: string | null;
      soloPrice?: number | null;
      soloLabel?: string | null;
      groupPrice?: number | null;
      groupLabel?: string | null;
    };
    taxiCard?: {
      title?: string | null;
      description?: string | null;
      routes?:
        | {
            label: string;
            id?: string | null;
          }[]
        | null;
    };
    goodToKnowCard?: {
      title?: string | null;
      facts?:
        | {
            label: string;
            id?: string | null;
          }[]
        | null;
    };
  };
  spotsSection?: {
    title?: string | null;
    subtitle?: string | null;
    spots?:
      | {
          name: string;
          level: string;
          levelColor?: ('bg-primary' | 'bg-accent' | 'bg-azure' | 'bg-azure-dark') | null;
          description: string;
          image?: (string | null) | Media;
          /**
           * External image URL (used if no uploaded image)
           */
          imageUrl?: string | null;
          stats?:
            | {
                value: string;
                label: string;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
  };
  typicalDaySection?: {
    title?: string | null;
    subtitle?: string | null;
    timeline?:
      | {
          time: string;
          icon?: ('sunrise' | 'waves' | 'utensils-crossed' | 'compass' | 'sunset' | 'sun' | 'star' | 'car') | null;
          title: string;
          desc: string;
          color?: ('bg-primary' | 'bg-accent' | 'bg-azure' | 'bg-azure-dark') | null;
          id?: string | null;
        }[]
      | null;
  };
  finalCtaSection?: {
    backgroundImage?: (string | null) | Media;
    /**
     * Used if no uploaded background image
     */
    backgroundImageUrl?: string | null;
    /**
     * Use newlines for line breaks in the heading.
     */
    title?: string | null;
    description?: string | null;
    primaryButtonText?: string | null;
    /**
     * Can be relative (e.g. /booking?…) — language prefix added automatically.
     */
    primaryButtonLink?: string | null;
    secondaryButtonText?: string | null;
    secondaryButtonLink?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Edit the /packages page — page header and final "Can't decide?" CTA.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "packages-page".
 */
export interface PackagesPage {
  id: string;
  /**
   * Search engine and social share metadata for this page
   */
  seo?: {
    /**
     * Shown in browser tab and search engines. Recommended: 50-60 characters.
     */
    metaTitle?: string | null;
    /**
     * Shown in search results. Recommended: 150-160 characters.
     */
    metaDescription?: string | null;
    /**
     * Comma-separated keywords (optional, low SEO impact today).
     */
    keywords?: string | null;
    /**
     * Shown when the page is shared on Facebook, Twitter, WhatsApp. Recommended: 1200x630px.
     */
    ogImage?: (string | null) | Media;
  };
  headerSection?: {
    breadcrumbLabel?: string | null;
    title?: string | null;
    subtitle?: string | null;
    ratingScore?: string | null;
    ratingSource?: string | null;
    infoChip1?: string | null;
    infoChip2?: string | null;
  };
  finalCtaSection?: {
    backgroundImage?: (string | null) | Media;
    /**
     * Used if no uploaded background image
     */
    backgroundImageUrl?: string | null;
    title?: string | null;
    description?: string | null;
    whatsappButtonText?: string | null;
    whatsappMessage?: string | null;
    emailButtonText?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Edit the Restaurant & Kitchen page — gallery, daily meals, full menu, food philosophy, and CTA.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "restaurant-page".
 */
export interface RestaurantPage {
  id: string;
  /**
   * Search engine and social share metadata for this page
   */
  seo?: {
    /**
     * Shown in browser tab and search engines. Recommended: 50-60 characters.
     */
    metaTitle?: string | null;
    /**
     * Shown in search results. Recommended: 150-160 characters.
     */
    metaDescription?: string | null;
    /**
     * Comma-separated keywords (optional, low SEO impact today).
     */
    keywords?: string | null;
    /**
     * Shown when the page is shared on Facebook, Twitter, WhatsApp. Recommended: 1200x630px.
     */
    ogImage?: (string | null) | Media;
  };
  /**
   * Breadcrumb and page title area
   */
  headerSection?: {
    title?: string | null;
    breadcrumbLabel?: string | null;
  };
  /**
   * Large hero image + 4 thumbnail grid at top of page (5 images total)
   */
  gallerySection?: {
    /**
     * First image is the large hero, next 4 appear as thumbnails on desktop. Upload up to 10 for the lightbox.
     */
    images?:
      | {
          image?: (string | null) | Media;
          alt?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Three meal cards — Breakfast, Lunch, BBQ Dinner
   */
  dailyMealsSection?: {
    eyebrow?: string | null;
    title?: string | null;
    subtitle?: string | null;
    meals?:
      | {
          title: string;
          time: string;
          description?: string | null;
          /**
           * e.g. "Included with Stay", "A la carte", "Signature"
           */
          badge?: string | null;
          image?: (string | null) | Media;
          /**
           * Dishes shown under "FROM THE MENU" on the card
           */
          dishes?:
            | {
                name: string;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * All menu categories and items — shown with filter buttons
   */
  menuSection?: {
    eyebrow?: string | null;
    title?: string | null;
    categories?:
      | {
          title: string;
          items?:
            | {
                name: string;
                /**
                 * Optional — e.g. "€5" or "5 €"
                 */
                price?: string | null;
                /**
                 * Optional — brief description of the dish
                 */
                description?: string | null;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Dark section with 4 icon+text philosophy items
   */
  philosophySection?: {
    title?: string | null;
    subtitle?: string | null;
    items?:
      | {
          icon: 'anchor' | 'leaf' | 'flame' | 'heart' | 'star' | 'utensils' | 'sun' | 'waves' | 'shield' | 'coffee';
          title: string;
          description?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Bottom CTA banner with WhatsApp and email links
   */
  ctaSection?: {
    title?: string | null;
    description?: string | null;
    whatsappButtonText?: string | null;
    /**
     * Used for wa.me link — format: 212772228120
     */
    whatsappNumber?: string | null;
    whatsappMessage?: string | null;
    emailButtonText?: string | null;
    email?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Edit the Blog page content - header section, search placeholder, and category labels.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-page".
 */
export interface BlogPage {
  id: string;
  /**
   * Search engine and social share metadata for this page
   */
  seo?: {
    /**
     * Shown in browser tab and search engines. Recommended: 50-60 characters.
     */
    metaTitle?: string | null;
    /**
     * Shown in search results. Recommended: 150-160 characters.
     */
    metaDescription?: string | null;
    /**
     * Comma-separated keywords (optional, low SEO impact today).
     */
    keywords?: string | null;
    /**
     * Shown when the page is shared on Facebook, Twitter, WhatsApp. Recommended: 1200x630px.
     */
    ogImage?: (string | null) | Media;
  };
  /**
   * The header at the top of the blog page
   */
  headerSection?: {
    eyebrow?: string | null;
    title?: string | null;
    subtitle?: string | null;
  };
  /**
   * Search and filter settings
   */
  filtersSection?: {
    searchPlaceholder?: string | null;
    allPostsLabel?: string | null;
  };
  /**
   * Messages shown when no posts are found
   */
  emptyState?: {
    noPostsTitle?: string | null;
    noPostsMessage?: string | null;
  };
  /**
   * Various labels used in blog cards
   */
  labels?: {
    readMoreText?: string | null;
    readText?: string | null;
    byAuthorPrefix?: string | null;
    minReadSuffix?: string | null;
    minSuffix?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Edit the Contact page content - header, contact info, opening hours, form labels, and map section.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-page".
 */
export interface ContactPage {
  id: string;
  /**
   * Search engine and social share metadata for this page
   */
  seo?: {
    /**
     * Shown in browser tab and search engines. Recommended: 50-60 characters.
     */
    metaTitle?: string | null;
    /**
     * Shown in search results. Recommended: 150-160 characters.
     */
    metaDescription?: string | null;
    /**
     * Comma-separated keywords (optional, low SEO impact today).
     */
    keywords?: string | null;
    /**
     * Shown when the page is shared on Facebook, Twitter, WhatsApp. Recommended: 1200x630px.
     */
    ogImage?: (string | null) | Media;
  };
  /**
   * The header at the top of the contact page
   */
  headerSection?: {
    badge?: string | null;
    /**
     * Use HTML styling like <span> for colored words
     */
    title?: string | null;
  };
  /**
   * The contact details card
   */
  contactInfoCard?: {
    title?: string | null;
    whatsappLabel?: string | null;
    whatsappNumber?: string | null;
    /**
     * Number without + for wa.me link
     */
    whatsappLink?: string | null;
    emailLabel?: string | null;
    email?: string | null;
    locationLabel?: string | null;
    location?: string | null;
  };
  /**
   * Social media links card
   */
  stayConnectedCard?: {
    title?: string | null;
    whatsappText?: string | null;
    instagramText?: string | null;
    instagramUrl?: string | null;
    tiktokText?: string | null;
    tiktokUrl?: string | null;
  };
  /**
   * Business hours card
   */
  openingHoursCard?: {
    title?: string | null;
    mondayFridayLabel?: string | null;
    mondayFridayHours?: string | null;
    saturdayLabel?: string | null;
    saturdayHours?: string | null;
    sundayLabel?: string | null;
    sundayHours?: string | null;
  };
  /**
   * Location map section
   */
  mapSection?: {
    badge?: string | null;
    title?: string | null;
    description?: string | null;
    mapEmbedUrl?: string | null;
    mapLocationName?: string | null;
    mapLocationCity?: string | null;
    getDirectionsText?: string | null;
    googleMapsUrl?: string | null;
  };
  /**
   * Form labels and messages
   */
  formSection?: {
    badge?: string | null;
    title?: string | null;
    description?: string | null;
    nameLabel?: string | null;
    namePlaceholder?: string | null;
    emailLabel?: string | null;
    emailPlaceholder?: string | null;
    phoneLabel?: string | null;
    phonePlaceholder?: string | null;
    subjectLabel?: string | null;
    subjectPlaceholder?: string | null;
    messageLabel?: string | null;
    messagePlaceholder?: string | null;
    submitButtonText?: string | null;
    submittingText?: string | null;
    clearFormText?: string | null;
    successMessage?: string | null;
    errorMessage?: string | null;
    quickContactText?: string | null;
    emailUsText?: string | null;
  };
  /**
   * The floating WhatsApp button settings
   */
  floatingWhatsapp?: {
    message?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Manage taxi / airport transfer routes and prices. Used by the booking wizard (Extras step) and the Surf page taxi card.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transfers".
 */
export interface Transfer {
  id: string;
  cardTitle?: string | null;
  cardDescription?: string | null;
  /**
   * Each route has a stable routeId (used by bookings), a localized label, and a price in EUR.
   */
  routes: {
    /**
     * Unique slug, e.g. "airport-imsouane". Do NOT change after bookings reference it.
     */
    routeId: string;
    label: string;
    /**
     * One-way price in EUR.
     */
    priceEur: number;
    /**
     * Uncheck to hide from the booking wizard and Surf page.
     */
    active?: boolean | null;
    id?: string | null;
  }[];
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Manage header, footer, and tracking settings - changes apply across all pages
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: string;
  /**
   * Configure the main navigation menu links
   */
  headerNavLinks?:
    | {
        label: string;
        /**
         * Use relative paths like /flights, /about, etc.
         */
        href: string;
        id?: string | null;
      }[]
    | null;
  headerCtaText?: string | null;
  headerCtaLink?: string | null;
  /**
   * Phone number without + sign, e.g. 212772228120
   */
  headerWhatsappNumber?: string | null;
  headerWhatsappText?: string | null;
  footerBrandDescription?: string | null;
  footerCopyrightText?: string | null;
  footerPhone?: string | null;
  footerEmail?: string | null;
  /**
   * Without + sign
   */
  footerWhatsappNumber?: string | null;
  footerLocation?: string | null;
  footerInstagramUrl?: string | null;
  footerTiktokUrl?: string | null;
  /**
   * Links in the "Experiences" column
   */
  footerExperiencesLinks?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Links in the "About" column
   */
  footerAboutLinks?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Your Google Ads ID (e.g., AW-123456789). Get this from Google Ads → Tools & Settings → Conversions
   */
  googleAdsId?: string | null;
  /**
   * Google Ads Conversion ID for tracking bookings (usually same as Google Ads ID)
   */
  googleAdsConversionId?: string | null;
  /**
   * Google Ads Conversion Label for tracking bookings (e.g., AbCdEfGhIjK)
   */
  googleAdsConversionLabel?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage_select".
 */
export interface HomepageSelect<T extends boolean = true> {
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        keywords?: T;
        ogImage?: T;
      };
  heroSection?:
    | T
    | {
        backgroundImage?: T;
        heroVideoUrl?: T;
        heroVideoMobileUrl?: T;
        heroVideoWebmUrl?: T;
        heroVideoMobileWebmUrl?: T;
        heroPosterUrl?: T;
        headline?: T;
        tagline?: T;
        description?: T;
        highlights?:
          | T
          | {
              icon?: T;
              label?: T;
              id?: T;
            };
        primaryButtonText?: T;
        primaryButtonLink?: T;
        secondaryButtonText?: T;
        secondaryButtonLink?: T;
      };
  aboutSection?:
    | T
    | {
        title?: T;
        titleAccent?: T;
        description?: T;
        stats?:
          | T
          | {
              value?: T;
              label?: T;
              id?: T;
            };
        experienceImage?: T;
        experienceTitle?: T;
        experienceFeatures?:
          | T
          | {
              title?: T;
              description?: T;
              id?: T;
            };
        experienceButtonText?: T;
        experienceButtonLink?: T;
      };
  roomsSection?:
    | T
    | {
        title?: T;
        titleAccent?: T;
        featuredRooms?: T;
      };
  surfSection?:
    | T
    | {
        title?: T;
        titleAccent?: T;
        description?: T;
        featuredActivities?: T;
      };
  packagesSection?:
    | T
    | {
        title?: T;
        titleAccent?: T;
        description?: T;
        featuredPackages?: T;
      };
  rentalsSection?:
    | T
    | {
        title?: T;
        titleAccent?: T;
        description?: T;
        fromPriceBadge?: T;
        soloNote?: T;
        groupNote?: T;
        cardTitle?: T;
        cardDescription?: T;
        features?:
          | T
          | {
              label?: T;
              icon?: T;
              id?: T;
            };
        displayPrice?: T;
        perDayLabel?: T;
        soloPricePerDay?: T;
        groupPricePerDay?: T;
        bookNowText?: T;
        form?:
          | T
          | {
              equipment?: T;
              boardOnly?: T;
              wetsuitOnly?: T;
              both?: T;
              startDate?: T;
              endDate?: T;
              quantity?: T;
              fullName?: T;
              email?: T;
              phone?: T;
              days?: T;
              day?: T;
              perPerson?: T;
              submit?: T;
              submitting?: T;
              successTitle?: T;
              successMessage?: T;
              errorGeneric?: T;
              errorDateOrder?: T;
            };
      };
  restaurantSection?:
    | T
    | {
        heroImage?: T;
        title?: T;
        titleAccent?: T;
        description?: T;
        meals?:
          | T
          | {
              title?: T;
              time?: T;
              description?: T;
              image?: T;
              id?: T;
            };
        philosophy?:
          | T
          | {
              title?: T;
              description?: T;
              id?: T;
            };
      };
  featureStrip?:
    | T
    | {
        features?:
          | T
          | {
              value?: T;
              label?: T;
              id?: T;
            };
      };
  reviewsSection?:
    | T
    | {
        title?: T;
        titleAccent?: T;
        ratingBadges?:
          | T
          | {
              score?: T;
              source?: T;
              label?: T;
              id?: T;
            };
        reviews?:
          | T
          | {
              name?: T;
              from?: T;
              quote?: T;
              dark?: T;
              id?: T;
            };
      };
  gallerySection?:
    | T
    | {
        title?: T;
        titleAccent?: T;
        images?: T;
        instagramUrl?: T;
      };
  locationSection?:
    | T
    | {
        title?: T;
        titleAccent?: T;
        description?: T;
        mapEmbedUrl?: T;
        phone?: T;
        email?: T;
        whatsappNumber?: T;
        address?: T;
        instagramUrl?: T;
        tiktokUrl?: T;
        routes?:
          | T
          | {
              from?: T;
              time?: T;
              id?: T;
            };
      };
  footer?:
    | T
    | {
        brandName?: T;
        brandTagline?: T;
        brandDescription?: T;
        copyrightText?: T;
        designCredit?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page_select".
 */
export interface AboutPageSelect<T extends boolean = true> {
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        keywords?: T;
        ogImage?: T;
      };
  heroSection?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        description?: T;
        ratingValue?: T;
        ratingLabel?: T;
        location?: T;
        backgroundImage?: T;
        imageAlt?: T;
      };
  storySection?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        ratingText?: T;
        description?: T;
        image?: T;
        imageAlt?: T;
        features?:
          | T
          | {
              label?: T;
              id?: T;
            };
      };
  experienceSection?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        ratingText?: T;
        description1?: T;
        description2?: T;
        image?: T;
        imageAlt?: T;
        features?:
          | T
          | {
              label?: T;
              id?: T;
            };
      };
  featureStrip?:
    | T
    | {
        items?:
          | T
          | {
              icon?: T;
              value?: T;
              label?: T;
              id?: T;
            };
      };
  experienceCards?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        subtitle?: T;
        cards?:
          | T
          | {
              icon?: T;
              title?: T;
              description?: T;
              image?: T;
              features?:
                | T
                | {
                    label?: T;
                    id?: T;
                  };
              id?: T;
            };
      };
  faqSection?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        contactText?: T;
        whatsappUrl?: T;
        whatsappLabel?: T;
        faqs?:
          | T
          | {
              question?: T;
              answer?: T;
              id?: T;
            };
      };
  ctaSection?:
    | T
    | {
        title?: T;
        subtitle?: T;
        backgroundImage?: T;
        primaryButtonText?: T;
        primaryButtonLink?: T;
        secondaryButtonText?: T;
        secondaryButtonLink?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rooms-page_select".
 */
export interface RoomsPageSelect<T extends boolean = true> {
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        keywords?: T;
        ogImage?: T;
      };
  headerSection?:
    | T
    | {
        breadcrumbLabel?: T;
        title?: T;
        subtitle?: T;
        ratingScore?: T;
        ratingSource?: T;
        infoChip1?: T;
        infoChip2?: T;
      };
  packagesCta?:
    | T
    | {
        title?: T;
        description?: T;
        buttonText?: T;
        buttonLink?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "surf-page_select".
 */
export interface SurfPageSelect<T extends boolean = true> {
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        keywords?: T;
        ogImage?: T;
      };
  headerSection?:
    | T
    | {
        breadcrumbLabel?: T;
        title?: T;
        subtitle?: T;
        ratingScore?: T;
        ratingSource?: T;
        infoChip1?: T;
        infoChip2?: T;
      };
  rentalsSection?:
    | T
    | {
        title?: T;
        subtitle?: T;
        surfboardCard?:
          | T
          | {
              title?: T;
              description?: T;
              soloPrice?: T;
              soloLabel?: T;
              groupPrice?: T;
              groupLabel?: T;
            };
        taxiCard?:
          | T
          | {
              title?: T;
              description?: T;
              routes?:
                | T
                | {
                    label?: T;
                    id?: T;
                  };
            };
        goodToKnowCard?:
          | T
          | {
              title?: T;
              facts?:
                | T
                | {
                    label?: T;
                    id?: T;
                  };
            };
      };
  spotsSection?:
    | T
    | {
        title?: T;
        subtitle?: T;
        spots?:
          | T
          | {
              name?: T;
              level?: T;
              levelColor?: T;
              description?: T;
              image?: T;
              imageUrl?: T;
              stats?:
                | T
                | {
                    value?: T;
                    label?: T;
                    id?: T;
                  };
              id?: T;
            };
      };
  typicalDaySection?:
    | T
    | {
        title?: T;
        subtitle?: T;
        timeline?:
          | T
          | {
              time?: T;
              icon?: T;
              title?: T;
              desc?: T;
              color?: T;
              id?: T;
            };
      };
  finalCtaSection?:
    | T
    | {
        backgroundImage?: T;
        backgroundImageUrl?: T;
        title?: T;
        description?: T;
        primaryButtonText?: T;
        primaryButtonLink?: T;
        secondaryButtonText?: T;
        secondaryButtonLink?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "packages-page_select".
 */
export interface PackagesPageSelect<T extends boolean = true> {
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        keywords?: T;
        ogImage?: T;
      };
  headerSection?:
    | T
    | {
        breadcrumbLabel?: T;
        title?: T;
        subtitle?: T;
        ratingScore?: T;
        ratingSource?: T;
        infoChip1?: T;
        infoChip2?: T;
      };
  finalCtaSection?:
    | T
    | {
        backgroundImage?: T;
        backgroundImageUrl?: T;
        title?: T;
        description?: T;
        whatsappButtonText?: T;
        whatsappMessage?: T;
        emailButtonText?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "restaurant-page_select".
 */
export interface RestaurantPageSelect<T extends boolean = true> {
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        keywords?: T;
        ogImage?: T;
      };
  headerSection?:
    | T
    | {
        title?: T;
        breadcrumbLabel?: T;
      };
  gallerySection?:
    | T
    | {
        images?:
          | T
          | {
              image?: T;
              alt?: T;
              id?: T;
            };
      };
  dailyMealsSection?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        subtitle?: T;
        meals?:
          | T
          | {
              title?: T;
              time?: T;
              description?: T;
              badge?: T;
              image?: T;
              dishes?:
                | T
                | {
                    name?: T;
                    id?: T;
                  };
              id?: T;
            };
      };
  menuSection?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        categories?:
          | T
          | {
              title?: T;
              items?:
                | T
                | {
                    name?: T;
                    price?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
            };
      };
  philosophySection?:
    | T
    | {
        title?: T;
        subtitle?: T;
        items?:
          | T
          | {
              icon?: T;
              title?: T;
              description?: T;
              id?: T;
            };
      };
  ctaSection?:
    | T
    | {
        title?: T;
        description?: T;
        whatsappButtonText?: T;
        whatsappNumber?: T;
        whatsappMessage?: T;
        emailButtonText?: T;
        email?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-page_select".
 */
export interface BlogPageSelect<T extends boolean = true> {
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        keywords?: T;
        ogImage?: T;
      };
  headerSection?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        subtitle?: T;
      };
  filtersSection?:
    | T
    | {
        searchPlaceholder?: T;
        allPostsLabel?: T;
      };
  emptyState?:
    | T
    | {
        noPostsTitle?: T;
        noPostsMessage?: T;
      };
  labels?:
    | T
    | {
        readMoreText?: T;
        readText?: T;
        byAuthorPrefix?: T;
        minReadSuffix?: T;
        minSuffix?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-page_select".
 */
export interface ContactPageSelect<T extends boolean = true> {
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        keywords?: T;
        ogImage?: T;
      };
  headerSection?:
    | T
    | {
        badge?: T;
        title?: T;
      };
  contactInfoCard?:
    | T
    | {
        title?: T;
        whatsappLabel?: T;
        whatsappNumber?: T;
        whatsappLink?: T;
        emailLabel?: T;
        email?: T;
        locationLabel?: T;
        location?: T;
      };
  stayConnectedCard?:
    | T
    | {
        title?: T;
        whatsappText?: T;
        instagramText?: T;
        instagramUrl?: T;
        tiktokText?: T;
        tiktokUrl?: T;
      };
  openingHoursCard?:
    | T
    | {
        title?: T;
        mondayFridayLabel?: T;
        mondayFridayHours?: T;
        saturdayLabel?: T;
        saturdayHours?: T;
        sundayLabel?: T;
        sundayHours?: T;
      };
  mapSection?:
    | T
    | {
        badge?: T;
        title?: T;
        description?: T;
        mapEmbedUrl?: T;
        mapLocationName?: T;
        mapLocationCity?: T;
        getDirectionsText?: T;
        googleMapsUrl?: T;
      };
  formSection?:
    | T
    | {
        badge?: T;
        title?: T;
        description?: T;
        nameLabel?: T;
        namePlaceholder?: T;
        emailLabel?: T;
        emailPlaceholder?: T;
        phoneLabel?: T;
        phonePlaceholder?: T;
        subjectLabel?: T;
        subjectPlaceholder?: T;
        messageLabel?: T;
        messagePlaceholder?: T;
        submitButtonText?: T;
        submittingText?: T;
        clearFormText?: T;
        successMessage?: T;
        errorMessage?: T;
        quickContactText?: T;
        emailUsText?: T;
      };
  floatingWhatsapp?:
    | T
    | {
        message?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transfers_select".
 */
export interface TransfersSelect<T extends boolean = true> {
  cardTitle?: T;
  cardDescription?: T;
  routes?:
    | T
    | {
        routeId?: T;
        label?: T;
        priceEur?: T;
        active?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  headerNavLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  headerCtaText?: T;
  headerCtaLink?: T;
  headerWhatsappNumber?: T;
  headerWhatsappText?: T;
  footerBrandDescription?: T;
  footerCopyrightText?: T;
  footerPhone?: T;
  footerEmail?: T;
  footerWhatsappNumber?: T;
  footerLocation?: T;
  footerInstagramUrl?: T;
  footerTiktokUrl?: T;
  footerExperiencesLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  footerAboutLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  googleAdsId?: T;
  googleAdsConversionId?: T;
  googleAdsConversionLabel?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}